import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import Link from 'next/link'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size:20x;
        }
        h3{
          font-size:15px;
        }`}

      </style>
    
    </div>
      <Head>
        <title>Blog Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={styles.main}>
      <h1 className= {styles.title}>
      <span className='hunter'>Hunting Coder</span>
      </h1>
      <div className={styles.imagewrap}>
      <Image className = {styles.myimg} src="/image1.jpg"  alt = "imaeg" width={113} height={78}/>
      {/* <image className={styles.myImg} src="/image1.jpg" width={237} height={158} alt="hunting coder" /> */}
      </div>
      <p className={styles.description}>
        Welcome to hunting Coder
      </p>

      <div className={styles.blogs}>
        <h2>Popular blogs </h2>
        <div className={styles.blogitems}>
        <h3>learn java script</h3>
        <p>explore the world of coding</p>
      </div>
      </div>
      
      <div className={styles.blogs}>
        <div className={styles.blogitems}>
        <h3>learn java script</h3>
        <p>explore the world of coding</p>
      </div>
      </div>
      <div className={styles.blogs}>
        <div className={styles.blogitems}>
        <h3>learn java script</h3>
        <p>explore the world of coding</p>
      </div>
      </div>
      <div className={styles.blogs}>
        <div className={styles.blogitems}>
        <h3>learn java script</h3>
        <p>explore the world of coding</p>
      </div>
      </div>
    </main>
    </>
  )
}
